baseURL = "https://rensdimmendaal.com/"
languageCode = "en-us"
title = "Rens"
theme = "xmin"
publishDir = "docs"


[permalinks]
    post = "/posts/:year/:month/:day/:slug/"
    note = "/notes/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A place to share things"
footer = "Website by [Hugo](https://gohugo.io). Theme by [Yihui Xie](https://yihui.name). Content by me. | [Github](https://github.com/rensdimmendaal) | [Twitter](https://twitter.com/r_dimm)"
